<a href="https://colab.research.google.com/github/Zero-Sik/Py_L/blob/master/NLPipynb.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 자연어 처리(natural language processing)란?


## 자연어란? 우리가 일상 생활에서 사용하는 언어를 말함.

 - 자연어처리(Natural language processing)란 이러한 자연어를 의미를 분석하여 컴퓨터가 처리할 수 있도록 하는 일을 말함.


  - 자연어 처리는 음성인식, 내용 요약, 번역, 사용자의 감성 분석, 텍스트 분류 작업(스팸 메일 분류, 뉴스 기사 카테고리 분류), 질의 응답 시스템, 챗봇과 같은 곳에서 사용 됨.

  - 최근 딥 러닝이 주목 받으면서 인공지능이 제 4차 산업혁명의 중요 키워드로 떠오르고 있음.
  - 자연어 처리는 기꼐에서 인간의 언어를 이해 시킨다는 점에서 인공지능에 있어서 가장 중요한 연구 분야이면서도, 아직도 정복되어야 할 산이 많은 분야임.
  - 인공지능 분야는 다윗이 골리앗을 이기는 것이 가능한 분야
  - 뛰어난 딥러닝 엔지니어 몇 명이면 딥 러닝을 이용하여 단 수일만에, 불과 몇 년 전에 실무에서 사용되었던 번역기들을 앞서는 번역기를 만들 수 있는 시대가 됨.
  - 전처리 방법(Preporcessing), 딥 러닝 주류로 사용되었던 통계 기반의 언어 모델, 자연어 처리의 비약적인 성능을 이루어낸 딥 러닝을 이용한 자연어 처리 대한 전반 지식을 야기할 것임.

###머신 러닝 실습을 하기 위해서는 많은 패키지가 필요
 -  일일히 설치하는 것보다 필요한 패키지들을 모아놓은 파이썬 배포판 '아나콘다'를 설치하는 것을 권장.
 - 아나콘다는 Numpy, Pandas, jupyter Notebook, IPyhon, scikit-learn, matplotilb, seaborn, nltk 등  포함



## 구글 코랩(Colab)
 - 개인의 컴퓨터 사양이나 다른 이유로 아나콘다나 여러 패키지 설치가 어려운 경우도 있다. 이런 경우 인터넷만 된다면 실습 환경을 사용할 수 있다.
 - 주니퍼 노트북 형식의 개발 환경.

# 필요 프레임워크와 라이브러리
 - 텐서플로우(Tensorflow)
  - 머신 러닝 오픈소스 라이브러리
   - 머신러닝과 딥 러닝을 직관적이고 손쉽게 할 수 있도록 설계
   

In [0]:
##설치 방법
# Tuminal - pip install tensorflow



#ipython


#import tensorflow as tf  텐서플로우는 tf라는 명칭으로 임포트하는 것이 관례

#tf.__version__


 ## 케라스
  - 딥러닝 프에미워크인 텐서플로우에 대한 추상화 된 API를 제공.
  - 백엔드 텐서플로우를 사용하며, 좀 더 쉽게 딥 러닝을 사용할 수 있게 해줌.
  - 케라스 개발자인 프랑소와 숄레(Francois Chollet)는 앞으로는 Keras보다는 tf.keras를 사용할 것을 권장.

In [0]:
#ipython



import keras
keras.__version__

Using TensorFlow backend.


'2.2.5'

## 젠심(Gensim)
 - 머신 러닝을 사용하여 토픽 모델링과 자연어 처리 등을 수행할 수 있게 해주는 오픈 소스 라이브러리
 - 토픽 모델링과 Word2Vec 등을 학습
굵은 텍스트

In [0]:
# pip install gensim


# ipython


import gensim
gensim.__version__

'3.6.0'

 ## 사이킷런(Scikit-learn)
  - 파이썬 머신러닝 라이브러리.
  - 사이킷런을 통해 나이브 베이즈 분류, 서포트 벡터 머신 등 다양한 머신러닝 모듈을 불러 올 수 가 있다.
  - 사이킷런에는 머신러닝을 연습하기 위한 아이리스 데이터, 당뇨병 데이터 등 자체 데이터 또한 제공


In [0]:
# pip install scikit-learn


# ipython


import sklearn

sklearn.__version__


'0.21.3'

# 판다스(Pandas) and 넘파이(Numpy) and 맷플롭립(Matplotlib)

 - 데이터 분석을 위한 필수 패키지 


 

## 판다스
 - 파이썬 데이터 처리를 위한 라이브러리.
 - 데이터 분석과 같은 작업에서 필수 라이브러리라고 알 수 있음.
  - 데이터 구조
   - 시리즈
   - 데이터 프레임
   - 패널


In [0]:
# pip install pandas
#ipython

import pandas as pd
pd.__version__


# 시리즈
 # - 1차원 배열의 값(values)에 값에 대응 되는 인덱스(index)를 부여할 수 있는 구조


sr = pd.Series([17000, 18000, 1000, 5000],
       index=["피자", "치킨", "콜라", "맥주"])
print(sr)

print(sr.values)

print(sr.index)


# 데이터 프레임(DataFrame)


  #2차원 리스트를 매개변수로 전달. 2차원이므로 행방향 인덱스와 열방향 인덱스가 존재
  #행과 열을 가지는 자료구조
  # 시리즈가 인덱스와 값으로 구성되었다면 데이터 프레임은 열까지 추가되어 열, 인덱스, 값으로 구성


values = [[1,2, 3], [4,5,6], [7,8,9]]
index = ['No:1', 'No:2', 'No:3']
columns= ['A', 'B', 'C']
print("-----------------------Series----")
df = pd.DataFrame(values, index=index, columns=columns)
print(df)


print(df.index) # 인덱스 호출
print(df.columns) # 열 출력
print(df.values) # 값 출력


# 생성

# 데이터 프레임은 리스트, 시리즈, 딕셔너리, Numpy의 ndarrays,또 다른 데이터프레임으로
 # 생성할 수 있음.


print("---------Data Insrt------------")
data = [
         ['1000', 'Steve', 90.72],
         ['1001', 'James', 78.72],
         ['1002', 'Doyeon', 98.72],
         ['1003', 'Jane', 64.19],
         ['1004', 'Pilwoong', 81.30],
         ['1005', 'Tony', 99.14],
 ]
 
df = pd.DataFrame(data)
print(df)

#생성된 데이터 프레임에 열(columns)을 지정해 줄 수 있습니다.

df = pd.DataFrame(data, columns=['학번', '이름', '점수'])
print(df)


print("파이썬 자료구조 중 딕셔너리(Dict)를 통해 데이터프레임을 생성.")

data = {'학번':['1000', '1001', '1002', '1003', '1004', '1005'],
        '이름' : ['Steve', 'James', 'Doyeon', 'Youngsik', 'Yuna', 'Mirae'],
        '점수': [90.55, 86.55, 55.43, 99.99, 94.22, 96.55]}


df = pd.DataFrame(data)

print(df)



# 조회

 # - 데이터프레임에서 원하는 구간만 확인.


# df.head(n) - 앞 부분을 n개만 보기
# df.tail(n) - 뒷 부분을 n개만 보기
# df['열이름'] - 해당되는 열을 확인

print(df.head(3)) # 앞 부분을 3개만 보기

print(df.tail(3)) # 뒷 부분 3개만 보기


print(df['학번']) # 학번에 해당되는 열을 보기







피자    17000
치킨    18000
콜라     1000
맥주     5000
dtype: int64
[17000 18000  1000  5000]
Index(['피자', '치킨', '콜라', '맥주'], dtype='object')
-----------------------Series----
      A  B  C
No:1  1  2  3
No:2  4  5  6
No:3  7  8  9
Index(['No:1', 'No:2', 'No:3'], dtype='object')
Index(['A', 'B', 'C'], dtype='object')
[[1 2 3]
 [4 5 6]
 [7 8 9]]
---------Data Insrt------------
      0         1      2
0  1000     Steve  90.72
1  1001     James  78.72
2  1002    Doyeon  98.72
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14
     학번        이름     점수
0  1000     Steve  90.72
1  1001     James  78.72
2  1002    Doyeon  98.72
3  1003      Jane  64.19
4  1004  Pilwoong  81.30
5  1005      Tony  99.14
파이썬 자료구조 중 딕셔너리(Dict)를 통해 데이터프레임을 생성.
     학번        이름     점수
0  1000     Steve  90.55
1  1001     James  86.55
2  1002    Doyeon  55.43
3  1003  Youngsik  99.99
4  1004      Yuna  94.22
5  1005     Mirae  96.55
     학번      이름     점수
0  1000   Steve  90.55
1  1001   James  86

## 판다스 외부 데이터 읽기
 - Pandas는 CSV, 텍스트, Excel, SQL, HTML, JSON 등 다양한 데이터 파일을 읽고 데이터 프레임을 생성할 수 있음


 

In [0]:
df = pd.read.csv("example.csv 파일의 경로") # example.csv 파일 읽기
# 예를 들어 윈도우 바탕화면에서 직업한 저자의 경우
# df=pd.read_csv(r'C:Users\User\Desktop\example.csv)로 할 것.
print(df)


# 인덱스가 자동으로 부여된 것을 볼 수 있습니다. 
print(df.index)


RangeIndex(start=0, stop=6, step=1)



# 넘파이(Numpy)

 - 수치 데이터를 다루는 파이썬 패키지
  - Numpy의 핵심이라고 불리는 다차원 행렬 자료구조인 ndarray를 통해 벡터 및 행렬을 사용하는 선형 대수 계산에서 주로 사용.
  - numpy는 편의성뿐만 아니라, 속도면에서도 순수 파이썬에 비해 압도적 빠르다는 장점.
 - Numpy의 경우, 주로 np라는 명칭으로 임포트 한다.



  -Numpy의 주요 모듈은 아래와 같다.
   - np.aaray() # 리스트 튜플, 배열로 부터 ndarray를 생성
   - np.asarray() 기존의 array로 부터 ndarray를 생성
   - np,arange() # range와 비슷
   - np.linspace(start, end  num) # [start, end] 균일한 간격으로 num개 생성
   - np.logspace(start, end, num) # [start, end] log scale 간격으로 num 개 생성
   



In [0]:
# pip install numpy

# ipython

import numpy as np

np.__version__

'1.17.4'

# np.array()
 - ndarray는 리스트, 튜플, 배열로 부터 ndarray를 생성합니다. 또한 인덱스가 항상 0으로 시작한다는 특징을 갖고 잇습니다.


 

In [0]:
a = np.array([1,2,3,4,5]) # 리스트를 가자고 1차원 배열 생성
print(type(a))
print(a)

<class 'numpy.ndarray'>
[1 2 3 4 5]


 - 타입이 numpy.ndaaray라고 나오고 있으며, 배열로 생성되었음.
 - 2차배열의 주의할 점은 array() 안에 하나의 리스트만 들어가므로 리스트의 리스트를 넣어야함.

 

In [0]:
b = np.array([[10,20,30], [40,50,60]])
print(b)

# 행렬의 차원 및 크기를 ndim 속성과 shape 속성으로 출력

print(b.shape)
print(a.ndim)





[[10 20 30]
 [40 50 60]]
(2, 3)
1


## ndarray의 초기화

- 위에서는 리스트 가지고 ndarray를 생성했지만, ndarray를 만드는 다양한 다른 방법이 존재
- zeros()는 해당 배열에 모두 0을 삽입하고, ones()는 모두 1을 삽입합니다.
- full()은 배열에 사용자가 지정한 값을 넣는데 사용하고, eye()는 대각선으로는 1이고 나머지는  0인 2차우너 배열을 생성


In [10]:
import numpy as np
print("-----zeros-----")
a = np.zeros((2,3)) # 모든값이 0인 2x3 배열 생성.
print(a)
print("-----ones-----")
a = np.ones((2,3)) # 모든 값이 1인 2 x 3 배열 생성
print(a)
print("-----eye-----")
a = np.eye(3) # 대각선으로는 1이고 나머지는 0인 2차원 배열을 생성
print(a)
print("-----random-----")
a = np.random.random((2,3)) # 임의의 값으로 채워진 배열 생성
print(a)








-----zeros-----
[[0. 0. 0.]
 [0. 0. 0.]]
-----ones-----
[[1. 1. 1.]
 [1. 1. 1.]]
-----eye-----
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
-----random-----
[[0.87113018 0.02214877 0.8869464 ]
 [0.33082513 0.30082392 0.99849225]]


## np.arange()

 - np.arange()는 지정해준 범위에 대해서 배열을 생성

- numpy.arange(start, stop, step, dtype)
- 
a = np.arange(n) # 0 , ...., n-1 까지 범위의 지정.
a = np.arange(i,j,k) # i부터 j-1까지 k씩 증가하는 배열


In [13]:
import numpy as np

a = np.arange(10) # 0부터 9까지
print(a)


a = np.arange(1, 10, 2) # 1부터 9까지 +2씩 적용하는 범위
print(a)




[0 1 2 3 4 5 6 7 8 9]
[1 3 5 7 9]


In [14]:
# reshape()
a = np.array(np.arange(30)).reshape((5,6))
print(a)

# 0부터 n-1 까지의 숫자를 생성하는 arange(n) 함수에 배열을 다차원으로 변형하는 
# reshape()를 통해 배열을 생성




[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


### Numpy 슬라이싱
 - ndarray를 통해 만든 다차원 배열은 파이썬의 리스트처럼 슬라이스(Slice) 기능을 지원
 

In [19]:
import numpy as np
a = np.array([[1, 2, 3], [4, 5, 6]])

b = a[0:2, 0:2]
print(b)

# 다차원 배열을 슬라이싱하기 위해서는 각 차원 별로 슬라이스 범위를 지정
print("다차원 배열 슬라이싱")
b =a[0, :]
print(b)


# 두번째 열 출력
print("두 번째 열 출력")
b=a[:,1]
print(b)


[[1 2]
 [4 5]]
다차원 배열 슬라이싱
[1 2 3]
두 번째 열 출력
[2 5]


### Numpy 정수 인덱싱(integer indexing)

- 정수 인덱싱은 원본 배열로부터 부분 배열을 구함.




In [21]:
import numpy as np

a = np.array([[1,2], [4,5], [7,8]])

b = a[[2,1],[1,0]] # [[row2, col1], [row1, col0]을 의미]
print(b)

[8 4]
