## Numpy의 연산과 함수


> Numpy는 배열에 대한 기본적인  사칙연산을 지원.



- Python의 Numpy 라이브러리는 기본적인 상수 연산이 가능합니다.

In [1]:
import numpy as np

array = np.random.randint(1, 10 , size=4).reshape(2,2)
result_array = array * 10
print(result_array)

[[60 50]
 [90 60]]


- 서로 다른 형태의 Numpy 연산이 가능합니다.


In [10]:
import numpy as np

array1 = np.arange(4).reshape(2,2)
print(array1)
print("------------------------")
array2 = np.arange(2)
print(array2)
print("---------------------")
array3 = array1 + array2
print(array3)
print("---------------------")

[[0 1]
 [2 3]]
------------------------
[0 1]
---------------------
[[0 2]
 [2 4]]
---------------------


In [15]:
import numpy as np

array1 = np.arange(0, 8).reshape(2,4)
print(array1)
print("-------------------------------------")
array2 = np.arange(0, 8).reshape(2,4)
array3 = np.concatenate([array1, array2], axis=0)
print(array3)
print("--------------------------------------")
array4 = np.arange(0,4).reshape(4,1)

print(array4)
print("----------------------------------")

print(array3 + array4)


[[0 1 2 3]
 [4 5 6 7]]
-------------------------------------
[[0 1 2 3]
 [4 5 6 7]
 [0 1 2 3]
 [4 5 6 7]]
--------------------------------------
[[0]
 [1]
 [2]
 [3]]
----------------------------------
[[ 0  1  2  3]
 [ 5  6  7  8]
 [ 2  3  4  5]
 [ 7  8  9 10]]


- Numpy의 마스킹 연산이 가능합니다.

In [18]:
import numpy as np

# Numpy 원소의 값을 조건에 따라 바꿀 때는 다음과 같이 합니다.
# 반복문을 이용할 때보다 매우 빠르게 동작합니다.
# 대체로 이미지 처리(Image Prossing)에서 자주 활용
array1 = np.arange(16).reshape(4,4)
print(array1)

print("---------------------------")

array2 = array1 <10
print(array2)
print("----------------------------")

array1[array2] = 1000
print(array1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
---------------------------
[[ True  True  True  True]
 [ True  True  True  True]
 [ True  True False False]
 [False False False False]]
----------------------------
[[1000 1000 1000 1000]
 [1000 1000 1000 1000]
 [1000 1000   10   11]
 [  12   13   14   15]]


- Numpy는 다양한 집계 함수가 존재합니다.



In [23]:
import numpy as np

array = np.arange(16).reshape(4, 4)

print("최대값:", np.max(array))
print("최소값:", np.min(array))
print("합계:", np.sum(array))
print("평균값:", np.mean(array))

최대값: 15
최소값: 0
합계: 120
평균값: 7.5


In [28]:
import numpy as np

array = np.arange(16).reshape(4,4)

print(array)

print("합계 : ", np.sum(array, axis=0))


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
합계 :  [24 28 32 36]
